### ISSUE TITLE
Research splitting template into barebones vs kitchen sink

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-sdk-template#6]
The add-in template has been split in to two.  A very vanilla example and a "kitchen sink" example.  This has worked well given there are generally two scenarios.  Someone that needs the absolutely bare-minimum for getting setup vs someone that's doing exploration and wants to see how the modules and process work.

I think we should evaluate the same setup for the default template.

Not to conflate this issue, but it will likely very quickly bleed in to Blackbaud vs 3rd-party differences as well.

(This issue will likely need to find a new home.)

**Comment by blackbaud-johnly** [comment]
Transferred from the docs repo. We don't have all of our tags in this repo, so I just wanted to note that we had placed the Severity as Low in the docs repo.

**Comment by Blackbaud-AlexKingman** [comment]
Severity: Low
Impact: Low

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl @Blackbaud-BenLambert I've created a new template repo for a "barebones" setup, performing the steps that Ben listed above. Let me know what you think: https://github.com/blackbaud/skyux-sdk-template-barebones

**Comment by Blackbaud-BobbyEarl** [comment]
I really like this Steve!  Do you think, even for the barebones, maybe we should go ahead and create the `app-sky.module.ts` just to instill best practices right out of the gate?

**Comment by blackbaud-johnly** [comment]
Will we need to update the docs at https://developer.blackbaud.com/skyux/learn/reference/template-items to reflect the barebones template?

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-johnly We'll need to document the new template name, but a better place might be under the `--template` details, here: https://developer.blackbaud.com/skyux/learn/reference/cli-commands/new#options. I created an issue: https://github.com/blackbaud/skyux2-docs/issues/695

@Blackbaud-BobbyEarl I created a pull request to address your comments, here: https://github.com/blackbaud/skyux-sdk-template-barebones/pull/1
